### ISSUE TITLE
Library has an unused route `/logout`

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-session-http#3]
https://github.com/digitalbazaar/bedrock-session-http/blob/d94a125b5a90fbace668708e34614e3ca4e7b166/lib/config.js#L15

https://github.com/digitalbazaar/bedrock-session-http/blob/d94a125b5a90fbace668708e34614e3ca4e7b166/lib/index.js#L18-L38

the route `/logout` was added in 2016, but appears to have never been used.

**Comment by dlongley** [comment]
Removed in version 4.
